[package]
name = "rbs"
version = "0.1.0"
edition = "2024"

[dependencies]
peek-again = { git = "https://github.com/CleveGreen/peek-again", branch = "main" }
ptrie = "0.7.2"

[build-dependencies]
serde = "1.0.219"
ptrie = "0.7.2"
serde_json = "1.0.142"
itertools = "0.14.0"
